name: CI
on:
  push:
      branches:
          - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: "npm"
      - run: npm install
      - run: npm run lint && npm run build